### ISSUE TITLE
[plugin:vite:css] Undefined variable

### ISSUE THREAD

**Issue by absolutelyrichd** [zougari47/portfolio-template#2]
Halo Ahmed, i found some error when try to run your awesome template
![image](https://github.com/zougari47/portfolio-template/assets/153931479/55c53e07-befa-458f-a4cb-d43c6a512a84)
i have been search on stackoverflow but it's not yet fix..
oh ya i'm newbie btw .

**Comment by zougari47** [comment]
I saw that you closed the issue. Did you fix the problem?

**Comment by absolutelyrichd** [comment]
ya it's fixed .
i try to create new variable for "primary-text-emphasis-dark" and it's work .
thanks for your attention.
