### ISSUE TITLE
Plane: Unable to create a Plane because the Renderer WebGL context is not defined

### ISSUE THREAD

**Issue by Kurumi30** [zougari47/portfolio-template#3]
The hero image is not displaying

- git clone https://github.com/zougari47/portfolio-template.git
- cd portfolio-template
- pnpm install && pnpm dev

Environment:
- Node v20.12.2
- pnpm 8.15.5

**Comment by zougari47** [comment]
Thank you @Kurumi30  for submitting this issue. 
I just tried these steps you provided and didn't get the problem 
Environment:
- Node v21.2.0
- pnpm 8.11.0

The deployment doesn't have this problem also. So I think it is something to your local environment. 

---
What browser you're using? 
Check this it might be helpful:
[https://stackoverflow.com/questions/54232528/error-creating-webgl-context-three-js-chrome](https://stackoverflow.com/questions/54232528/error-creating-webgl-context-three-js-chrome)

Let me know If you solve it!

**Comment by Kurumi30** [comment]
Appreciate your response!

> What browser you're using? Check this it might be helpful: https://stackoverflow.com/questions/54232528/error-creating-webgl-context-three-js-chrome

I am using 
- Windows 10 PRO
- Chrome version 126.0.6478.127 – 64 bits
- GPU: AMD Radeon HD 6410D

I believe it is an issue with the GPU😥
![image](https://github.com/zougari47/portfolio-template/assets/96603684/0392a512-467e-43ae-90e0-2e30dc08ea6f)

**Comment by zougari47** [comment]
Sadly as I expected. You can still add your photo and you will not face any problem at deployment.
Other users will find it normal.
